#!/usr/bin/env python3
"""Render the eval gate's golden set from the shipped book plus the hand-written oracle.

The gate's INPUTS (client profiles, holdings, house views) come from
``cio_advisory/data/demo_book/``, so the clients the gate measures are the clients the demo
shows. Before this, the golden set restated two clients of its own, and a change to the book
moved what the demo narrated without moving what the gate measured.

The gate's EXPECTATIONS stay in ``eval/expectations.json``, written by hand. That separation
is the whole design: rendering the expectations from the book too would ask the code under
test whether it agrees with itself, every metric would read 1.000, and the gate would be
decoration. When the engine and the oracle disagree, one of them is wrong and a person
decides which.

Run it after any change to the book or the oracle, and commit the result::

    python scripts/render_golden.py
    python scripts/render_golden.py --check   # non-zero when the committed file is stale

``--check`` runs in the offline gate, so a book edit that was never rendered fails the build
rather than leaving the gate measuring yesterday's clients.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO_ROOT / "src"))

from cio_advisory import demo_book  # noqa: E402

_ORACLE = _REPO_ROOT / "eval" / "expectations.json"
_OUTPUT = _REPO_ROOT / "eval" / "datasets" / "golden_clients.jsonl"

_HEADER = """\
# GENERATED by scripts/render_golden.py from the shipped demo book plus eval/expectations.json.
# Do not hand-edit: `python scripts/render_golden.py --check` fails the offline gate when this
# file no longer matches its two sources, which is how a book edit that never reached the gate
# gets caught.
#
# The INPUTS below (client_profile, portfolio, house_views) are the book's, so the gate
# measures the clients the demo shows. The EXPECTATIONS (expected_suitability_verdicts,
# expected_allocation_gaps, expected_threat_exposures) are hand-written in
# eval/expectations.json and are deliberately NOT derived from the book: an oracle computed
# from the thing under test agrees with it by construction and measures nothing.
#
# pii_in_inputs=true makes run_eval.py append that market's national identifier to the client
# id, which is the one client-controlled string the pipeline redacts, so pii_safety proves the
# redactor masks the pack this client is actually booked under. All data is fictional.
"""


def render() -> str:
    """The golden set as text, one JSON object per line, in book order."""
    demo_book.validate()
    oracle = json.loads(_ORACLE.read_text(encoding="utf-8"))["clients"]
    profiles = demo_book.rows("client_profiles")
    instruments = {r["instrument_id"]: r for r in demo_book.rows("instruments")}
    holdings: dict[str, list[dict]] = {}
    for row in demo_book.rows("holdings"):
        holdings.setdefault(row["client_id"], []).append(row)
    views = [
        {
            "id": v["id"],
            "theme": v["theme"],
            "stance": v["stance"],
            "asset_class": v["asset_class"],
            "rationale": v["rationale"],
            "tags": v.get("tags", []),
        }
        for v in demo_book.house_view_rows()
    ]

    lines = [_HEADER]
    for profile in profiles:
        client_id = profile["client_id"]
        expected = oracle.get(client_id)
        if expected is None:
            continue  # a client with no hand-written oracle is not a gate case
        record = {
            "id": expected["id"],
            "client_id": client_id,
            "client_profile": {
                "risk_appetite": profile["risk_appetite"],
                "objectives": profile.get("objectives", []),
                "knowledge_experience": profile.get("knowledge_experience", "informed"),
                "constraints": profile.get("constraints", []),
                "jurisdiction": profile.get("jurisdiction", "SG"),
            },
            "portfolio": [
                {
                    "instrument": instruments[h["instrument_id"]]["name"],
                    "asset_class": instruments[h["instrument_id"]]["asset_class"],
                    "value": h["value"],
                    "weight": h["weight"],
                    "currency": h.get("currency", "USD"),
                    "tags": instruments[h["instrument_id"]].get("theme_tags", []),
                }
                for h in sorted(holdings[client_id], key=lambda r: int(r["line_no"]))
            ],
            "house_views": views,
            "expected_suitability_verdicts": expected["expected_suitability_verdicts"],
            "expected_allocation_gaps": expected["expected_allocation_gaps"],
            "expected_threat_exposures": expected["expected_threat_exposures"],
            "expected_addressed_gaps": expected["expected_addressed_gaps"],
            "pii_in_inputs": expected.get("pii_in_inputs", False),
        }
        lines.append(json.dumps(record))
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero when the committed golden set is not what the sources render",
    )
    args = parser.parse_args(argv)
    rendered = render()
    if args.check:
        current = _OUTPUT.read_text(encoding="utf-8") if _OUTPUT.exists() else ""
        if current != rendered:
            print(
                f"{_OUTPUT.relative_to(_REPO_ROOT)} is stale: the demo book or "
                "eval/expectations.json changed. Run: python scripts/render_golden.py",
                file=sys.stderr,
            )
            return 1
        print(f"{_OUTPUT.relative_to(_REPO_ROOT)} matches the book and the oracle")
        return 0
    _OUTPUT.write_text(rendered, encoding="utf-8")
    cases = rendered.count("\n") - _HEADER.count("\n")
    print(f"rendered {_OUTPUT.relative_to(_REPO_ROOT)}: {cases} golden cases")
    return 0


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    raise SystemExit(main())
